/**
 * A private company, assessed twice and never once.
 *
 * A listed counter has a price the market argues about every day. A private
 * deal has an asking price and a deck, so the tool's job is different: hold the
 * asking price against two independent views and print where they disagree.
 *
 *   The private equity lens buys today's earnings at a comparable multiple,
 *   discounted for the fact that nobody can sell this on a Tuesday.
 *   The venture lens buys the exit and backs out what may be paid today for a
 *   return that clears the hurdle.
 *
 * They rarely agree. The disagreement is the finding, so it is printed rather
 * than averaged away. Averaging two views produces a number no one holds.
 */
import { irr } from "./analysis.js";

/** What the deck says it will look like at the exit. Assumptions, and labelled so. */
export interface Projection {
  /** Years from now to the exit. */
  years: number;
  exitRevenue: number;
  exitEbitda: number;
  /** EV/EBITDA the buyer is assumed to pay at exit. */
  exitMultiple: number;
  /** Debt less cash at the exit. Subtracted to get equity. */
  netDebtAtExit: number;
}

/** What is being asked for, and for how much of the company. */
export interface Terms {
  /** The cheque. */
  investment: number;
  /** Valuation before the cheque. */
  preMoney: number;
  /**
   * The share of the company still held at exit after later rounds. One means
   * no further dilution, which almost never happens and should be argued for.
   */
  dilutionRetention: number;
}

/** A listed company standing in for the unlisted one. */
export interface Anchor {
  name: string;
  evEbitda: number;
  /**
   * What is taken off for the fact that this cannot be sold on a Tuesday.
   * Stated, never folded silently into the multiple.
   */
  illiquidityDiscount: number;
}

/** Today's figures for the company being bought. */
export interface Today {
  revenue: number;
  ebitda: number;
  netDebt: number;
  /** Cash generated by operations. The number that says whether the EBITDA is real. */
  cashFromOperations: number | null;
  receivables: number | null;
  /** Share of revenue from the largest customer. */
  largestCustomerShare: number | null;
  /** Share of revenue from parties connected to the owners. */
  relatedPartyShare: number | null;
}

// ---------------------------------------------------------------- the venture lens

export interface VentureView {
  exitEquity: number;
  /** What the whole equity may be worth today at the hurdle. */
  supportedValuationToday: number;
  /** The share the money must own at exit to earn the hurdle. */
  requiredOwnershipAtExit: number;
  /** The share the terms actually give, before later dilution. */
  offeredOwnershipNow: number;
  /** The share those terms leave at exit, after the stated dilution. */
  ownershipAtExit: number;
  /** The value of that share at exit. */
  proceeds: number;
  impliedIrr: number | null;
  targetIrr: number;
  clears: boolean;
  /** The premium (positive) or discount (negative) of the asking price to what is supported. */
  askVersusSupported: number;
}

export function ventureView(p: Projection, t: Terms, targetIrr: number): VentureView {
  const exitEquity = Math.max(0, p.exitEbitda * p.exitMultiple - p.netDebtAtExit);
  const postMoney = t.preMoney + t.investment;
  const offered = postMoney > 0 ? t.investment / postMoney : 0;
  const atExit = offered * t.dilutionRetention;
  const proceeds = atExit * exitEquity;

  const discountFactor = Math.pow(1 + targetIrr, p.years);
  // What the money needs to own at exit, then what that implies the whole
  // company may be worth today.
  const requiredAtExit = exitEquity > 0 ? (t.investment * discountFactor) / exitEquity : Infinity;
  const supportedPost = requiredAtExit > 0 && Number.isFinite(requiredAtExit)
    ? t.investment / (requiredAtExit / t.dilutionRetention)
    : 0;
  const supportedPre = Math.max(0, supportedPost - t.investment);

  return {
    exitEquity,
    supportedValuationToday: supportedPre,
    requiredOwnershipAtExit: requiredAtExit,
    offeredOwnershipNow: offered,
    ownershipAtExit: atExit,
    proceeds,
    impliedIrr: irr(t.investment, proceeds, p.years),
    targetIrr,
    clears: proceeds >= t.investment * discountFactor,
    askVersusSupported: supportedPre > 0 ? t.preMoney / supportedPre - 1 : Infinity,
  };
}

// ---------------------------------------------------------------- the private equity lens

export interface PrivateEquityView {
  anchor: string;
  /** The comparable's multiple, before the discount. */
  quotedMultiple: number;
  /** After it. This is what is actually paid. */
  appliedMultiple: number;
  illiquidityDiscount: number;
  enterpriseValue: number;
  equityValue: number;
  /** Premium (positive) or discount (negative) of the asking price to this. */
  askVersusValue: number;
  clears: boolean;
}

export function privateEquityView(today: Today, anchor: Anchor, t: Terms): PrivateEquityView {
  const applied = anchor.evEbitda * (1 - anchor.illiquidityDiscount);
  const ev = today.ebitda * applied;
  const equity = ev - today.netDebt;
  return {
    anchor: anchor.name,
    quotedMultiple: anchor.evEbitda,
    appliedMultiple: applied,
    illiquidityDiscount: anchor.illiquidityDiscount,
    enterpriseValue: ev,
    equityValue: equity,
    askVersusValue: equity > 0 ? t.preMoney / equity - 1 : Infinity,
    clears: equity >= t.preMoney,
  };
}

// ---------------------------------------------------------------- is the profit real

export interface Flag {
  test: string;
  finding: string;
  failed: boolean;
}

export interface QualityOfEarnings {
  score: number;
  outOf: number;
  flags: Flag[];
  verdict: string;
}

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const days = (x: number) => `${Math.round(x)} days`;

/**
 * Five tests on whether the earnings in the deck are earnings.
 *
 * A test that cannot run because the deck does not give the figure is not a
 * pass. It is reported as unanswered, which is itself a finding about the deck.
 */
export function qualityOfEarnings(today: Today, projection: Projection): QualityOfEarnings {
  const flags: Flag[] = [];

  if (today.cashFromOperations === null) {
    flags.push({ test: "Cash conversion", finding: "The deck gives no operating cash flow. Ask for it before anything else.", failed: true });
  } else {
    const conversion = today.ebitda > 0 ? today.cashFromOperations / today.ebitda : 0;
    flags.push({
      test: "Cash conversion",
      finding: `${pct(conversion)} of EBITDA arrived as cash.` +
        (conversion < 0.5 ? " Below half: the profit is on paper until proven otherwise." : ""),
      failed: conversion < 0.5,
    });
  }

  if (today.receivables === null) {
    flags.push({ test: "Receivable days", finding: "No receivables figure, so nothing can be said about collection.", failed: true });
  } else {
    const d = today.revenue > 0 ? (today.receivables / today.revenue) * 365 : 0;
    flags.push({
      test: "Receivable days",
      finding: `${days(d)} of revenue sitting in receivables.` + (d > 90 ? " Over ninety: revenue is being booked well before it is collected." : ""),
      failed: d > 90,
    });
  }

  if (today.largestCustomerShare === null) {
    flags.push({ test: "Customer concentration", finding: "The deck does not say who the customers are.", failed: true });
  } else {
    flags.push({
      test: "Customer concentration",
      finding: `${pct(today.largestCustomerShare)} of revenue from one customer.` +
        (today.largestCustomerShare > 0.3 ? " Losing them is the whole thesis." : ""),
      failed: today.largestCustomerShare > 0.3,
    });
  }

  if (today.relatedPartyShare === null) {
    flags.push({ test: "Related parties", finding: "No related-party disclosure. Assume there is something to disclose.", failed: true });
  } else {
    flags.push({
      test: "Related parties",
      finding: `${pct(today.relatedPartyShare)} of revenue from connected parties.` +
        (today.relatedPartyShare > 0.1 ? " That revenue leaves with the owners." : ""),
      failed: today.relatedPartyShare > 0.1,
    });
  }

  // The projection has to be reachable from where the company is standing.
  const growth = today.revenue > 0 && projection.years > 0
    ? Math.pow(projection.exitRevenue / today.revenue, 1 / projection.years) - 1
    : 0;
  flags.push({
    test: "Projected growth",
    finding: `Revenue is projected to compound at ${pct(growth)} for ${projection.years} years.` +
      (growth > 0.5 ? " Above fifty per cent a year, sustained. Almost nothing does this." : ""),
    failed: growth > 0.5,
  });

  const failed = flags.filter((f) => f.failed).length;
  const score = flags.length - failed;
  return {
    score, outOf: flags.length, flags,
    verdict: failed === 0 ? "The earnings survive the tests the deck allows."
      : failed <= 2 ? "Two questions to settle in diligence before this is a number."
      : "The earnings are not established. Nothing else in this memo means much yet.",
  };
}

// ---------------------------------------------------------------- what the money costs

export interface CapitalStack {
  equityIn: number;
  debtIn: number;
  rate: number;
  interest: number;
  interestCover: number | null;
  amortYears: number;
  annualService: number;
  serviceCover: number | null;
  sustainable: boolean;
  finding: string;
}

/**
 * `brian` §4: if borrowing, interest sustainability is modelled before entry,
 * not after. Cover is against today's EBITDA, never the projection - a lender
 * is repaid from what the company earns, not from what the deck hopes.
 */
export function capitalStack(args: {
  investment: number; debtShare: number; rate: number; amortYears: number; ebitda: number;
}): CapitalStack {
  const debtIn = args.investment * args.debtShare;
  const equityIn = args.investment - debtIn;
  const interest = debtIn * args.rate;
  const principal = args.amortYears > 0 ? debtIn / args.amortYears : 0;
  const service = interest + principal;
  const cover = interest > 0 ? args.ebitda / interest : null;
  const serviceCover = service > 0 ? args.ebitda / service : null;
  const sustainable = debtIn === 0 || (cover !== null && cover >= 3 && serviceCover !== null && serviceCover >= 1.25);

  return {
    equityIn, debtIn, rate: args.rate, interest,
    interestCover: cover, amortYears: args.amortYears, annualService: service,
    serviceCover, sustainable,
    finding: debtIn === 0
      ? "All equity. Nothing to service, and nothing to amplify either."
      : sustainable
        ? `EBITDA covers interest ${cover!.toFixed(1)}× and full service ${serviceCover!.toFixed(2)}×. The debt holds on today's earnings.`
        : `EBITDA covers interest ${cover === null ? "—" : cover.toFixed(1)}× and full service ${serviceCover === null ? "—" : serviceCover.toFixed(2)}×. ` +
          "Below three and 1.25 times: this only works if the projection does, which is not a plan.",
  };
}

// ---------------------------------------------------------------- the committee

export interface Committee {
  ventureSays: string;
  privateEquitySays: string;
  agree: boolean;
  finding: string;
  recommendation: "BUY" | "HOLD" | "SELL";
}

/**
 * Both lenses, and the gap between them named. Two lenses that agree are a
 * strong signal. Two that disagree are the more common and more useful case,
 * because the reason for the gap is the thing to negotiate.
 */
export function committee(
  vc: VentureView, pe: PrivateEquityView, qoe: QualityOfEarnings, stack: CapitalStack,
): Committee {
  const agree = vc.clears === pe.clears;
  const ventureSays = vc.clears
    ? `Clears ${pct(vc.targetIrr)} at ${pct(vc.ownershipAtExit)} of the exit.`
    : `Returns ${vc.impliedIrr === null ? "no solvable rate" : pct(vc.impliedIrr)} against a ${pct(vc.targetIrr)} hurdle.`;
  const privateEquitySays = pe.clears
    ? `Asking price sits ${pct(-pe.askVersusValue)} below ${pe.anchor} at ${pe.appliedMultiple.toFixed(1)}× after the illiquidity discount.`
    : `Asking price is ${pct(pe.askVersusValue)} above what ${pe.anchor} supports at ${pe.appliedMultiple.toFixed(1)}× after the illiquidity discount.`;

  let finding: string;
  if (agree && vc.clears) finding = "Both lenses clear. The price works on today's earnings and on the exit.";
  else if (agree) finding = "Neither lens clears. The asking price is not supported by today's earnings or by the exit.";
  else if (vc.clears) {
    finding = "The exit carries this and today's earnings do not: the whole case rests on the projection. " +
      "That is a venture position, so size it as one and do not call it value.";
  } else {
    finding = "Today's earnings carry this and the exit does not: the buyer is paying for a business, " +
      "not for growth. Fine, provided nobody is underwriting the deck.";
  }

  const recommendation: Committee["recommendation"] =
    qoe.score < qoe.outOf - 2 ? "SELL"
      : !stack.sustainable ? "HOLD"
      : agree && vc.clears ? "BUY"
      : agree ? "SELL"
      : "HOLD";

  return { ventureSays, privateEquitySays, agree, finding, recommendation };
}
